The changes to reproduce the issue happening to WEB Indexing, see stack trace below.
The idea how to do this came from here:
https://community.oracle.com/thread/2384888


ERROR [WatchDog_0] - Component [Load Groups:LOAD_GROUPS] finished with
status ERROR.
 Cannot add nonexistent properties to groups: ProductName,
ProductCategoryName
ERROR [WatchDog_0] - Error details:
org.jetel.exception.JetelRuntimeException: Component [Load
Groups:LOAD_GROUPS] finished with status ERROR.
	at org.jetel.graph.Node.createNodeException(Node.java:535)
	at org.jetel.graph.Node.run(Node.java:514)
	at java.lang.Thread.run(Thread.java:722)
Caused by: org.apache.axis2.AxisFault: Cannot add nonexistent properties
to groups: ProductName, ProductCategoryName
	at
org.apache.axis2.description.OutInAxisOperationClient$NonBlockingInvocationWorker.run(OutInAxisOperation.java:451)
	at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	... 1 more